version: "3.9"

networks:
  server-network:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "nginx-blog-server"
    ports:
      - 8888:80
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  # pandoc:
  #   container_name: pandoc-generator
  #   image: pandoc/core:3.1.1.0
  #   volumes:
  #     - ./content:/content
  #     - ./src:/src
